"""relieflink URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from Relieflink_apk import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('log',views.log),
    # path('register',views.register),
    # path('register_post',views.register_post),
    # path('donate',views.donation_add),
    #
    # path('donation_post',views.donation_post),
    # path('',views.home),
    # # path('login_post',views.login_post),
    # path('',views.Login_page),
    path('loginpage',views.loginpage),
    path('',views.index),
    path('login_buttonclick',views.login_buttonclick),
    path('addcamp',views.addcamp),
    path('addcamp_registerbuttonclick',views.addcamp_registerbuttonclick),
    path('updatecamp/<id>',views.updatecamp),
    path('updatecamp_updatebuttonclick/<id>',views.updatecamp_updatebuttonclick),
    path('viewcamp',views.viewcamp),
    path('delete_camp/<id>',views.delete_camp),
    path('viewvolunteer',views.viewvolunteer),
    path('viewuser',views.viewuser),
    path('addhospital',views.addhospital),
    path('addpolice_registerbuttonclick',views.addpolice_registerbuttonclick),
    path('addhospital_registerbuttonclick', views.addhospital_registerbuttonclick),
    path('viewhospital',views.viewhospital),
    path('delete_hospital/<id>', views.delete_hospital),
    path('updatehospital/<id>',views.updatehospital),
    path('updatehospital_updatebuttonclick/<id>',views.updatehospital_updatebuttonclick),
    path('addpolice',views.addpolice),
    path('updatepolice/<id>',views.updatepolice),
    path('updatepolice_updatebuttonclick/<id>',views.updatepolice_updatebuttonclick),
    path('viewpolice',views.viewpolice),
    path('delete_police/<id>', views.delete_police),
    path('addfire',views.addfire),
    path('addfire_registerbuttonclick',views.addfire_registerbuttonclick),
    path('addnotification_addbuttonclick',views.addnotification_addbuttonclick),
    path('updatefire/<id>',views.updatefire),
    path('updatefire_updatebuttonclick/<id>',views.updatefire_updatebuttonclick),
    path('viewfire',views.viewfire),
    path('delete_fire/<id>', views.delete_fire),
    path('viewdonation',views.viewdonation),
    path('addnotification',views.addnotification),
    path('updatenotification/<id>',views.updatenotification),
    path('updatenotification_updatebuttonclick/<id>',views.updatenotification_updatebuttonclick),
    path('viewnotification',views.viewnotification),
    path('delete_notification/<id>', views.delete_notification),
    path('addweather',views.addweather),
    path('addweather_addbuttonclick',views.addweather_addbuttonclick),
    path('updateweather/<id>',views.updateweather),
    path('updateweather_updatebuttonclick/<id>',views.updateweather_updatebuttonclick),
    path('viewweather',views.viewweather),
    path('delete_weather/<id>', views.delete_weather),
    path('adddeath',views.adddeath),
    path('adddeath_addbuttonclick',views.adddeath_addbuttonclick),
    path('updatedeath/<id>',views.updatedeath),
    path('updatedeath_updatebuttonclick/<id>',views.updatedeath_updatebuttonclick),
    path('viewdeath',views.viewdeath),
    path('delete_death/<id>', views.delete_death),
    path('addub',views.addub),
    path('updateub/<id>',views.updateub),
    path('updateub_updatebuttonclick/<id>',views.updateub_updatebuttonclick),
    path('addub_addbuttonclick',views.addub_addbuttonclick),
    path('viewub',views.viewub),
    path('delete_ub/<id>', views.delete_ub),
    path('viewmissingperson',views.viewmissingperson),
    path('delete_missing/<id>', views.delete_missing),
    path('viewalertandverify',views.viewalertandverify),
    path('logout_buttonclick', views.logout_buttonclick),
    path('adminlanding',views.adminlanding),
    path('verify/<id>',views.verify),
###############################################################################################################
    path('coordinator_home',views.coordinator_home),
    path('coordinator_view_profile',views.coordinator_view_profile),
    path('add_inmates_post',views.add_inmates_post),
    path('add_inmates',views.add_inmates),
    path('view_volunteer',views.view_volunteer),
    path('approve_volunteer/<id>',views.approve_volunteer),
    path('reject_volunteer/<id>',views.reject_volunteer),
    path('delete_requirement/<id>',views.delete_requirement),
    path('add_requirement',views.add_requirement),
    path('add_requirement_post',views.add_requirement_post),
    path('view_requirement',views.view_requirement),
    path('edit_requirement/<id>',views.edit_requirement),
    path('edit_requirement_post/<id>',views.edit_requirement_post),
    path('view_willing_users/<id>',views.view_willing_users),
    path('allocate_collection/<id>',views.allocate_collection),
    path('allocate_collectiont_post/<id>',views.allocate_collectiont_post),
    path('camp_view_disaster_notification',views.camp_view_disaster_notification),
    path('camp_view_weather',views.camp_view_weather),
    path('add_missing_person',views.add_missing_person),
    path('add_missing_person_post',views.add_missing_person_post),
    path('view_missing_person',views.view_missing_person),
    path('delete_missing_person/<id>',views.delete_missing_person),
    path('edit_missing_person/<id>',views.edit_missing_person),
    path('edit_missing_person_post/<id>',views.edit_missing_person_post),
    path('camp_view_volunteer_request',views.camp_view_volunteer_request),
    path('allocate_request/<id>',views.allocate_request),
    path('allocate_request_post/<id>',views.allocate_request_post),
    path('view_allocate_request/<id>',views.view_allocate_request),
    path('view_work_status/<id>',views.view_work_status),
    path('view_reporting/<id>',views.view_reporting),
        ################################################################################################
    path('volunteer_home',views.volunteer_home),
    path('view_profile',views.view_profile),
    path('view_collection_duty',views.view_collection_duty),
    path('update_collection_request/<id>',views.update_collection_request),
    path('volunteer_view_allocation',views.volunteer_view_allocation),
    path('update_work_status/<id>',views.update_work_status),
    path('update_work_status_post/<id>',views.update_work_status_post),
    path('volunteer_view_disaster_notification',views.volunteer_view_disaster_notification),
    path('volunteer_view_weather',views.volunteer_view_weather),
    path('volunteer_view_education_content',views.volunteer_view_education_content),
    path('volunteer_register',views.volunteer_register),
    path('volunteer_register_action',views.volunteer_register_action),
    #####################################################################################################


    path('public_view_weather',views.public_view_weather),
    path('public_view_disaster_notification',views.public_view_disaster_notification),
    path('public_view_missing_person',views.public_view_missing_person),
    path('public_view_camp',views.public_view_camp),
    path('public_view_deathtoll',views.public_view_deathtoll),
    path('public_home',views.public_home),
    #######################################################################################################
    # path('user_login',views.user_login),
    # path('view_disaster_notification',views.view_disaster_notification),
    # path('view_death_toll',views.view_death_toll),
    # path('view_weather_user',views.view_weather_user),
    # path('view_capm_user',views.view_capm_user),
    # path('view_plolicestation',views.view_plolicestation),
    ######################################################################################################

    path('user_view_near_by_policestations',views.user_view_near_by_policestations),
    path('user_view_firestation',views.user_view_firestation),
    path('user_view_camps',views.user_view_camps),
    path('user_view_requirements/<id>',views.user_view_requirements),
    path('add_to_willing/<id>',views.add_to_willing),
    path('user_send_volunteer_support_request/<id>',views.user_send_volunteer_support_request),
    path('user_view_assigned_volunteers',views.user_view_assigned_volunteers),
    path('user_view_disaster_notification',views.user_view_disaster_notification),
    path('user_view_deathtoll',views.user_view_deathtoll),
    path('user_view_weather',views.user_view_weather),
    path('user_view_ub',views.user_view_ub),
    path('report_missing_person_place/<id>',views.report_missing_person_place),
    path('user_report_missing_person/<id>',views.user_report_missing_person),
    path('user_add_alert',views.user_add_alert),
    path('user_add_alert_post',views.user_add_alert_post),
    path('user_view_alert',views.user_view_alert),
    path('user_delete_alert/<id>',views.user_delete_alert),
    path('user_edit_alert/<id>',views.user_edit_alert),
    path('user_edit_alert_post/<id>',views.user_edit_alert_post),
    path('user_view_missing_person',views.user_view_missing_person),
    path('user_delete_missing_person/<id>',views.user_delete_missing_person),
    path('user_edit_missing_person/<id>',views.user_edit_missing_person),
    path('user_edit_missing_person_post/<id>',views.user_edit_missing_person_post),
    path('user_registr',views.user_registr),
    path('user_registrations',views.user_registrations),
    path('user_add_missing_person_post',views.user_add_missing_person_post),
    path('user_add_missing_person',views.user_add_missing_person),
    path('user_home',views.user_home),




]
