# Generated by Django 2.0.9 on 2024-08-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('Coordinator_name', models.CharField(max_length=50)),
                ('Contact_no', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Latitude', models.CharField(max_length=10)),
                ('Longitude', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('Id_proof', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=50)),
                ('Skill', models.CharField(max_length=50)),
                ('Contact_no', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('CAMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.camp')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.login')),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.login'),
        ),
    ]
