# Generated by Django 2.0.9 on 2025-01-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disastercategory', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duty', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='deathtoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisasterType', models.CharField(max_length=100)),
                ('DeathCount', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_no', models.CharField(max_length=200)),
                ('Amount', models.CharField(max_length=200)),
                ('Transaction_id', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='firestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=50)),
                ('Pin', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=50)),
                ('Pin', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='inmates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Dateofadmission', models.CharField(max_length=500)),
                ('Dateofvacate', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='missingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.login')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisasterCategory', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=500)),
                ('Area', models.CharField(max_length=50)),
                ('Latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='policestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=50)),
                ('Pin', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='requirment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemrequired', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='unidentifiedbodies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampCoordinator', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('Hospital', models.CharField(max_length=50)),
                ('Male', models.CharField(max_length=50)),
                ('Female', models.CharField(max_length=50)),
                ('Kids', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Place', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('Contact_no', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='volunteerAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duty', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Workstatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weather', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='willingusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Item', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Contact_no', models.CharField(max_length=500)),
                ('Place', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='Number_of_inmates',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='CAMP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.camp'),
        ),
        migrations.AddField(
            model_name='volunteerallocation',
            name='Volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.volunteer'),
        ),
        migrations.AddField(
            model_name='requirment',
            name='Camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.camp'),
        ),
        migrations.AddField(
            model_name='inmates',
            name='Camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.camp'),
        ),
        migrations.AddField(
            model_name='collection',
            name='Volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.volunteer'),
        ),
    ]
