# Generated by Django 2.0.9 on 2025-01-08 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0002_auto_20250104_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='Volunteer',
            new_name='VOLUNTEER',
        ),
        migrations.RenameField(
            model_name='inmates',
            old_name='Camp',
            new_name='CAMP',
        ),
        migrations.RenameField(
            model_name='requirment',
            old_name='Camp',
            new_name='CAMP',
        ),
        migrations.RenameField(
            model_name='volunteerallocation',
            old_name='Volunteer',
            new_name='VOLUNTEER',
        ),
        migrations.RemoveField(
            model_name='willingusers',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='willingusers',
            name='Item',
        ),
        migrations.AddField(
            model_name='willingusers',
            name='REQUIREMENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.requirment'),
            preserve_default=False,
        ),
    ]
