# Generated by Django 2.0.9 on 2025-01-08 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0003_auto_20250108_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userregister',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='willingusers',
            name='Contact_no',
        ),
        migrations.RemoveField(
            model_name='willingusers',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='willingusers',
            name='Place',
        ),
        migrations.RemoveField(
            model_name='willingusers',
            name='Username',
        ),
        migrations.AddField(
            model_name='willingusers',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.user'),
            preserve_default=False,
        ),
    ]
