# Generated by Django 2.0.9 on 2025-01-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0004_auto_20250108_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
    ]
