# Generated by Django 2.0.9 on 2025-01-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0005_auto_20250108_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.login'),
            preserve_default=False,
        ),
    ]
