# Generated by Django 2.0.9 on 2025-01-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0006_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection_duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VOLUNTEER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.volunteer')),
                ('WILLING_USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.willingusers')),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='VOLUNTEER',
        ),
        migrations.DeleteModel(
            name='collection',
        ),
    ]
