# Generated by Django 2.0.9 on 2025-01-08 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0007_auto_20250108_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='LOGIN',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='CAMP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.camp'),
            preserve_default=False,
        ),
    ]
