# Generated by Django 2.0.9 on 2025-01-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0008_auto_20250108_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='CAMP',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missingperson',
            name='type',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
