# Generated by Django 2.0.9 on 2025-01-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0009_auto_20250108_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer_support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('CAMP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.camp')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.user')),
            ],
        ),
    ]
