# Generated by Django 2.0.9 on 2025-01-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0010_volunteer_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerallocation',
            old_name='Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='volunteerallocation',
            name='Duty',
        ),
        migrations.RemoveField(
            model_name='volunteerallocation',
            name='Place',
        ),
        migrations.RemoveField(
            model_name='volunteerallocation',
            name='Workstatus',
        ),
        migrations.AddField(
            model_name='volunteerallocation',
            name='VOLUNTEER_SUPPORT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.volunteer_support'),
            preserve_default=False,
        ),
    ]
