# Generated by Django 2.0.9 on 2025-01-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0011_auto_20250108_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='workstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=500)),
                ('VOLUNTEER_ALLOCATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.volunteerAllocation')),
            ],
        ),
    ]
