# Generated by Django 2.0.9 on 2025-01-08 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0012_workstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=500)),
                ('MISSING_PERSON', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.missingPerson')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.user')),
            ],
        ),
        migrations.DeleteModel(
            name='donation',
        ),
    ]
