# Generated by Django 2.0.9 on 2025-01-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0013_auto_20250108_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_duty',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
