# Generated by Django 2.0.9 on 2025-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0014_collection_duty_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='education_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
