# Generated by Django 2.0.9 on 2025-01-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relieflink_apk', '0015_education_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidentifiedbodies',
            name='CampCoordinator',
        ),
        migrations.RemoveField(
            model_name='unidentifiedbodies',
            name='Hospital',
        ),
        migrations.AddField(
            model_name='unidentifiedbodies',
            name='CAMP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.camp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidentifiedbodies',
            name='HOSPITAL',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Relieflink_apk.hospital'),
            preserve_default=False,
        ),
    ]
